name: base
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - astroid=2.4.2=py37_0
  - conda=4.8.5=py37_0
  - coverage
  - coveralls
  - idna=2.10=py_0
  - matplotlib
  - numpy
  - pandas
  - pip
  - pylint=2.6.0=py37_0
  - pyserial=3.4=py_2
  - pyvisa=1.10.1=py37hc8dfbb8_3
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - pip:
    - exhale==0.2.3
