name: build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest, generate coverage report
      run: |
        $CONDA/envs/base/bin/pytest --cov=./rcwa/source --cov-report xml

    - name: Upload coverage report to codecov
      uses: codecov/codecov-action@v1
      with: 
        token: ${{ secrets.codecov_token }}
        files: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true

    - name: Build python package tarball
      run:
        $CONDA/bin/python setup.py sdist bdist_wheel
    - name: Publish distribution to test PyPi
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_test_password2 }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true
    - name: Download and install from TestPyPi
      run:
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple rcwa
    - name: Run full testPyPi test suite
      run:
        python -m rcwa.test.fullRunner
    - name: Find me my branch name
      run: 
        echo ${{github.ref}}
    - name: Publish distribution to PyPi
      uses: pypa/gh-action-pypi-publish@master
      if: github.ref == 'refs/heads/master'
      with:
        user: __token__
        password: ${{ secrets.pypi_password2 }}
        verbose: true
    - name: Download from PyPi
      run:
        pip uninstall -y rcwa;
        pip install rcwa
    - name: Run full PyPi Test Suite
      run:
        python -m rcwa.test.fullRunner
